### ISSUE TITLE
TAssetPtr and FStringAssetReference have been renamed

### ISSUE THREAD

**Issue by dwrpayne** [FaceFX/FaceFX-UE4#112]
From the 4.18 release notes:

New: Cross-level Actor references are now better supported, using SoftObjectPath and SoftObjectPtr (called Soft Object Reference in Blueprints). As part of this, FStringAssetReference and TAssetPtr were renamed to FSoftObjectPath and TSoftObjectPtr.

**Comment by jcredmond** [comment]
The plugin compiles in 4.18 with no deprecation warnings and no errors.

Is this enforced? If so, since when? Epic didn’t follow their normal rename / deprecation procedure then. Usually, for deprecation Epic marks stuff to emit warnings and then actually removes it out a release or two later. For renames, however, they typically just rename it such that it produces a compilation error. 

The old names are still there and still work.  Is this causing a problem for you?

**Comment by jcredmond** [comment]
@oliverzx do you any insight to this?

**Comment by oliverzx** [comment]
You both are right. Epic indeed renamed things like _TAssetPtr_ & _FStringAssetReference_ (among some others) and deprecated them. Yet they didn't do it like they usually do with giving warnings. But that's purely not to spam the build log to the customers - which is a questionable decision imho.

They even commented on those on the redirectors:
`// Not deprecating these yet as it will lead to too many warnings in games`
`//DEPRECATED(4.18, "FStringAssetReference was renamed to FSoftObjectPath as it is now not always a string and can also refer to a subobject")`
`typedef FSoftObjectPath FStringAssetReference;`

`// Not deprecating these yet as it will lead to too many warnings in games`
`//DEPRECATED(4.18, "TAssetPtr was renamed to TSoftObjectPtr as it is not necessarily an asset")`
`template<class T=UObject>`
`using TAssetPtr = TSoftObjectPtr<T>;`

So yes, we should fix them until the next release.

**Comment by jcredmond** [comment]
Ok, I can do that today.

**Comment by jcredmond** [comment]
I used ripgrep and sed on macOS to do this (macOS sed requires the empty argument after -i, unlike Linux):

```Shell
$ rg -l TAssetPtr | xargs sed -i '' 's/TAssetPtr/TSoftObjectPtr/g'
$ rg -l FStringAssetReference | xargs sed -i '' 's/FStringAssetReference/FSoftObjectPath/g'
```

Then I built a rocket build for the official 4.18.0 release (no warnings or errors), and everything worked; though I did not do *extensive* testing.
